name: tinytots_staff
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cherry_toast: ^1.12.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  supabase_flutter: ^2.8.3
  hugeicons: ^0.0.7
  image_picker: ^1.1.2
  timeago: ^3.2.2
  cached_network_image: ^3.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    