name: tinytots_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/baby.png
    - assets/baloon.png
    - assets/watercolor.png 
    - assets/logo1.png
    - assets/bg.png  
    - assets/family.png
    - assets/logo3.png