name: tinytots_parent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cherry_toast: ^1.12.0
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

